[world]
name = "Octa Flip"
description = "Octa Flip game on Starknet"
cover_uri = "https://octaflip.com"
icon_uri = "https://octaflip.com"
website = "https://octaflip.com"
seed = "octaflipsepolia5"


[world.socials]
x = "https://octaflip.com"
discord = "https://octaflip.com"
github = "https://octaflip.com"
telegram = "https://octaflip.com"

[namespace]
default = "octa_flip"

[env]
world_address = "0x061017a1419eed9689c0dcb7b9d242cb489a4961f3ae884e1d92bfad0288958d"

[writers]
"octa_flip" = ["octa_flip-actions"]
