[world]
name = "Octa Flip"
description = "Dominate your world"
cover_uri = "https://cover.octaflip.com"
icon_uri = "https://icon.octaflip.com"
website = "https://octaflip.com"
seed = "octaflipv2"


[world.socials]
x = "https://x.octaflip.com"
discord = "https://discord.octaflip.com"
github = "https://github.octaflip.com"
telegram = "https://telegram.octaflip.com"

[namespace]
default = "octa_flip"

[env]

[writers]
"octa_flip" = ["octa_flip-GameActions"]
