[world]
name = "Octa Flip"
description = "Octa Flip game on Starknet"
cover_uri = "https://octaflip.com"
icon_uri = "https://octaflip.com"
website = "https://octaflip.com"
seed = "octaflipsepolia7"

[world.socials]
x = "https://octaflip.com"
discord = "https://octaflip.com"
github = "https://octaflip.com"
telegram = "https://octaflip.com"

[namespace]
default = "octa_flip"

[env]

[writers]
"octa_flip" = ["octa_flip-GameActions"]
